# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a base for building the application
FROM node:18-alpine AS builder

# Set the working directory in the container to /app
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package.json package-lock.json ./

# Install the project dependencies, ignoring any scripts to prevent build errors
RUN npm install --ignore-scripts

# Copy the source code into the container
COPY src src
COPY tsconfig.json ./

# Build the application
RUN npm run build

# Use a smaller Node.js image to run the application
FROM node:18-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set the command to run the application
ENTRYPOINT ["node", "build/index.js"]
